# Generated by Django 4.2.2 on 2023-12-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
