# Generated by Django 4.2.2 on 2023-12-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_comments_active_alter_comments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='author',
        ),
    ]
