# Generated by Django 4.2.2 on 2023-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='story_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
